In [1]:
import pandas as pd

acquis_trav = pd.read_csv("C:/Users/gromm/Downloads/Proprio_VS_Locataires_AcquisitionTravaux.csv")
display(acquis_trav)

,Acquisition de logements et travaux,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,en milliards d’euros
2,Au 31 décembre,2005.0,2010.0,2015.0,2018
3,Investissement en logements neufs1,64.7,66.1,57.7,72.4
4,Acquisition de logements anciens1,141.9,155.9,167.1,214.6
5,Travaux,36.8,44.1,47.1,50.2
6,Total,243.4,266.1,271.8,337.2
7,1. Y c. frais et droits liés.,NaN,NaN,NaN,NaN
8,"Source : SDES, compte satellite du logement, b...",NaN,NaN,NaN,NaN

In [2]:
acquis_trav.columns = ["acquisition_et_travaux", "2005", "2010", "2015", "2018"]
acquis_trav = acquis_trav.drop(acquis_trav.index[:3])
acquis_trav = acquis_trav.drop(acquis_trav.index[-2:])
display(acquis_trav)

               acquisition_et_travaux   2005   2010   2015   2018
3  Investissement en logements neufs1   64.7   66.1   57.7   72.4
4   Acquisition de logements anciens1  141.9  155.9  167.1  214.6
5                             Travaux   36.8   44.1   47.1   50.2
6                               Total  243.4  266.1  271.8  337.2

In [3]:
acquis_trav.to_csv("AcquisitionEtTravaux.csv", index = False)