In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/data/Projet_reconversion/Projet et cours Data Analyst/Cours Le Wagon/projet_crise_logement/données a traiter/DVF_MEL_2020_2025.csv", sep="|", parse_dates=["Date mutation"], dayfirst=True)

regroupement des biens 1 ventes = 1 ligne

In [ ]:
df.head()

,Date mutation,Valeur fonciere,Type local,Surface reelle bati,Nombre pieces principales,Commune,Code departement,Code postal,Surface terrain
0,2020-07-01,"339700,00",Maison,213.0,9.0,RONCHIN,59,59790.0,191.0
1,2020-07-01,"339700,00",Dépendance,0.0,0.0,RONCHIN,59,59790.0,15.0
2,2020-07-01,"339700,00",NaN,NaN,NaN,RONCHIN,59,59790.0,48.0
3,2020-07-01,"339700,00",NaN,NaN,NaN,RONCHIN,59,59790.0,536.0
4,2020-07-03,"550000,00",Maison,210.0,7.0,LILLE,59,59000.0,215.0

In [ ]:
df = df[df["Type local"].isin(["Maison", "Appartement"])]

df["Date mutation"] = pd.to_datetime(df["Date mutation"], errors="coerce")

df["Code postal"] = df["Code postal"].astype(str)

df["Valeur fonciere"] = (df["Valeur fonciere"].str.replace(",", ".", regex=False))

df["Valeur fonciere"] = pd.to_numeric(df["Valeur fonciere"], errors="coerce")

df["prix_m2"] = (df["Valeur fonciere"] / df["Surface reelle bati"]).round(2)

In [ ]:
df["Valeur fonciere"] = df["Valeur fonciere"].ffill()

In [ ]:
df

,Date mutation,Valeur fonciere,Type local,Surface reelle bati,Nombre pieces principales,Commune,Code departement,Code postal,Surface terrain,prix_m2
0,2020-07-01,339700.0,Maison,213.0,9.0,RONCHIN,59,59790.0,191.0,1594.84
4,2020-07-03,550000.0,Maison,210.0,7.0,LILLE,59,59000.0,215.0,2619.05
5,2020-07-03,166500.0,Maison,64.0,3.0,LILLE,59,59800.0,176.0,2601.56
6,2020-07-06,259000.0,Maison,92.0,4.0,MARQUETTE-LEZ-LILLE,59,59520.0,266.0,2815.22
9,2020-07-02,264000.0,Maison,156.0,5.0,RONCHIN,59,59790.0,110.0,1692.31
...,...,...,...,...,...,...,...,...,...,...
219515,2025-06-12,613899.0,Appartement,130.0,5.0,LA MADELEINE,59,59110.0,NaN,4722.30
219518,2025-06-23,52000.0,Appartement,27.0,1.0,ROUBAIX,59,59100.0,NaN,1925.93
219519,2025-06-24,731760.0,Maison,160.0,6.0,WAMBRECHIES,59,59118.0,847.0,4573.50
219520,2025-06-30,390000.0,Maison,85.0,5.0,LAMBERSART,59,59130.0,289.0,4588.24
219521,2025-06-27,155000.0,Maison,60.0,4.0,LEERS,59,59115.0,70.0,2583.33

In [ ]:
df.info()

<class 'pandas.DataFrame'>
Index: 99799 entries, 0 to 219521
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Date mutation              99799 non-null  datetime64[us]
 1   Valeur fonciere            99799 non-null  float64
 2   Type local                 99799 non-null  str
 3   Surface reelle bati        99765 non-null  float64
 4   Nombre pieces principales  99765 non-null  float64
 5   Commune                    99799 non-null  str
 6   Code departement           99799 non-null  int64
 7   Code postal                99799 non-null  str
 8   Surface terrain            63605 non-null  float64
 9   prix_m2                    99348 non-null  float64
dtypes: datetime64[us](1), float64(5), int64(1), str(3)
memory usage: 8.4 MB

In [ ]:
df["Valeur fonciere"] = df["Valeur fonciere"].fillna(df["Valeur fonciere"].mean())
df

KeyError: 'Valeur fonciere'