<a href="https://colab.research.google.com/github/augu-gif/Projet_crise_logement/blob/main/Processed/Immobilier/Nettoyage_de_donn%C3%A9es_DVF_2020_2025_MEL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

importation des données par années

In [3]:
df_2020 = pd.read_csv("/content/drive/MyDrive/Projet_crise_logement/Données_brut/Immobilier/Ventes_immobilière_2020_2025/ValeursFoncieres-2020-S2.csv", sep="|",low_memory=False)

In [4]:
df_2021 = pd.read_csv("/content/drive/MyDrive/Projet_crise_logement/Données_brut/Immobilier/Ventes_immobilière_2020_2025/ValeursFoncieres-2021.csv", sep="|",low_memory=False)

In [5]:
df_2022 = pd.read_csv("/content/drive/MyDrive/Projet_crise_logement/Données_brut/Immobilier/Ventes_immobilière_2020_2025/ValeursFoncieres-2022.csv", sep="|",low_memory=False)

In [6]:
df_2023 = pd.read_csv("/content/drive/MyDrive/Projet_crise_logement/Données_brut/Immobilier/Ventes_immobilière_2020_2025/ValeursFoncieres-2023.csv", sep="|",low_memory=False)

In [7]:
df_2024 = pd.read_csv("/content/drive/MyDrive/Projet_crise_logement/Données_brut/Immobilier/Ventes_immobilière_2020_2025/ValeursFoncieres-2024.csv", sep="|",low_memory=False)

In [8]:
df_2025 = pd.read_csv("/content/drive/MyDrive/Projet_crise_logement/Données_brut/Immobilier/Ventes_immobilière_2020_2025/ValeursFoncieres-2025-S1.csv", sep="|",low_memory=False)

In [9]:
df_2021.columns

Index(['Identifiant de document', 'Reference document', '1 Articles CGI',
       '2 Articles CGI', '3 Articles CGI', '4 Articles CGI', '5 Articles CGI',
       'No disposition', 'Date mutation', 'Nature mutation', 'Valeur fonciere',
       'No voie', 'B/T/Q', 'Type de voie', 'Code voie', 'Voie', 'Code postal',
       'Commune', 'Code departement', 'Code commune', 'Prefixe de section',
       'Section', 'No plan', 'No Volume', '1er lot',
       'Surface Carrez du 1er lot', '2eme lot', 'Surface Carrez du 2eme lot',
       '3eme lot', 'Surface Carrez du 3eme lot', '4eme lot',
       'Surface Carrez du 4eme lot', '5eme lot', 'Surface Carrez du 5eme lot',
       'Nombre de lots', 'Code type local', 'Type local', 'Identifiant local',
       'Surface reelle bati', 'Nombre pieces principales', 'Nature culture',
       'Nature culture speciale', 'Surface terrain'],
      dtype='object')

visualisation du nom des colonnes

In [10]:
cols = [
    "Date mutation",
    "Commune",
    "Code postal",
    "Nature mutation",
    "Type local",
    "Valeur fonciere",
    "Surface reelle bati"
]

df_2020 = df_2020[cols]

sélection des colonnes exploitable

In [11]:
df_2021 = df_2021[cols]

In [12]:
df_2022 = df_2022[cols]

In [13]:
df_2023 = df_2023[cols]

In [14]:
df_2024 = df_2024[cols]

In [15]:
df_2025 = df_2025[cols]

affinache des données pour concatenation

In [16]:
df_concat = pd.concat([df_2020, df_2021, df_2022, df_2023, df_2024, df_2025],
    axis=0,
    join="inner",
    ignore_index=True
)

In [17]:
df_concat.isna().sum()

Date mutation                0
Commune                      0
Code postal             151600
Nature mutation              0
Type local             8212317
Valeur fonciere         194390
Surface reelle bati    8225123
dtype: int64

In [18]:
df_concat.to_csv("DVF_MEL_concat.csv", index=False, sep="|")

filtre par code postal de la mel

In [63]:
df_mel = pd.read_excel("/content/drive/MyDrive/Projet_crise_logement/Données_nettoyées/Clef_communes/INSEE_CODEPOSTAL.xlsx")

In [64]:
code_departement = df_mel["CODE_POSTAL"].tolist()

In [65]:
df = df_concat[df_concat["Code postal"].isin(code_departement)]

utilisation du code postal pour prendre les villes de la mel

In [66]:
df

,Date mutation,Commune,Code postal,Nature mutation,Type local,Valeur fonciere,Surface reelle bati
1176358,01/07/2020,RONCHIN,59790.0,Vente,Maison,"339700,00",213.0
1176359,01/07/2020,RONCHIN,59790.0,Vente,Dépendance,"339700,00",0.0
1176360,01/07/2020,RONCHIN,59790.0,Vente,NaN,"339700,00",NaN
1176361,01/07/2020,RONCHIN,59790.0,Vente,NaN,"339700,00",NaN
1176362,03/07/2020,LILLE,59000.0,Vente,Maison,"550000,00",210.0
...,...,...,...,...,...,...,...
19528366,16/06/2025,VILLENEUVE-D'ASCQ,59491.0,Vente,Appartement,"104500,00",47.0
19528367,24/06/2025,WAMBRECHIES,59118.0,Vente,Maison,"731760,00",160.0
19528368,30/06/2025,LAMBERSART,59130.0,Vente,Maison,"390000,00",85.0
19528369,27/06/2025,LEERS,59115.0,Vente,Maison,"155000,00",60.0
19528370,27/06/2025,LEERS,59115.0,Vente,Dépendance,"155000,00",0.0

In [67]:
df.dtypes

Date mutation           object
Commune                 object
Code postal            float64
Nature mutation         object
Type local              object
Valeur fonciere         object
Surface reelle bati    float64
dtype: object

In [69]:
df = df[df["Type local"].isin(["Maison", "Appartement"])]

df["Date mutation"] = pd.to_datetime(df["Date mutation"], dayfirst=True)

df["Code postal"] = df["Code postal"].astype(int).astype(str)

df["Valeur fonciere"] = (df["Valeur fonciere"].str.replace(",", ".", regex=False))

df["Valeur fonciere"] = pd.to_numeric(df["Valeur fonciere"], errors="coerce")

df["prix_m2"] = (df["Valeur fonciere"] / df["Surface reelle bati"]).round(2)

df_mel["CODE_POSTAL"] = df_mel["CODE_POSTAL"].astype(str)

transformation du type des colonnes pour power BI

In [70]:
df.dtypes

Date mutation          datetime64[ns]
Commune                        object
Code postal                    object
Nature mutation                object
Type local                     object
Valeur fonciere               float64
Surface reelle bati           float64
prix_m2                       float64
dtype: object

In [71]:
df.isna().sum()

Date mutation            0
Commune                  0
Code postal              0
Nature mutation          0
Type local               0
Valeur fonciere        408
Surface reelle bati     27
prix_m2                435
dtype: int64

In [72]:
df = df.dropna()

suppression des valeurs null

In [73]:
df["Valeur fonciere"].min()

1.0

In [74]:
df = df[
    (df["Surface reelle bati"] >= 10) &
    (df["Surface reelle bati"] <= 500) &
    (df["Valeur fonciere"] >= 10000) &
    (df["Valeur fonciere"] <= 2000000)
]

In [75]:
df["prix_m2"].min()

36.47

In [76]:
df = df[(df["prix_m2"] >= 300) & (df["prix_m2"] <= 10000)]

In [77]:
df.shape

(81374, 8)

In [78]:
df["Commune"].nunique()

104

suppression des valeurs abérrantes

In [79]:
communes_a_supprimer = [
    "BACHY",
    "BOURGHELLES",
    "CAMPHIN-EN-PEVELE",
    "COBRIEUX",
    "CYSOING",
    "TRESSIN",
    'LOUVIL',
    "WANNEHAIN"
]

df = df[~df["Commune"].isin(communes_a_supprimer)]

In [80]:
df["Commune"] = df["Commune"].replace({
    "FACHES THUMESNIL": "FACHES-THUMESNIL",
    "MONS EN BAROEUL": "MONS-EN-BAROEUL",

})

In [81]:
df = df.merge(
    df_mel,
    left_on="Code postal",
    right_on="CODE_POSTAL",
    how="left"
)

In [85]:
df = df.drop(columns=["INSEE", "LIBVILLE", "CODE_POSTAL", "N_INSEE"])

In [86]:
df

,Date mutation,Commune,Code postal,Nature mutation,Type local,Valeur fonciere,Surface reelle bati,prix_m2,LIB_COM_POSTAL
0,2020-07-01,RONCHIN,59790,Vente,Maison,339700.0,213.0,1594.84,"Ronchin 59790,France"
1,2020-07-03,LILLE,59000,Vente,Maison,550000.0,210.0,2619.05,"Lille,France"
2,2020-07-06,MARQUETTE-LEZ-LILLE,59520,Vente,Maison,259000.0,92.0,2815.22,"Marquette-lez-Lille 59520,France"
3,2020-07-02,RONCHIN,59790,Vente,Maison,264000.0,156.0,1692.31,"Ronchin 59790,France"
4,2020-07-06,LILLE,59000,Vente,Appartement,140000.0,34.0,4117.65,"Lille,France"
...,...,...,...,...,...,...,...,...,...
117842,2025-06-23,ROUBAIX,59100,Vente,Appartement,52000.0,27.0,1925.93,"Roubaix 59100,France"
117843,2025-06-16,VILLENEUVE-D'ASCQ,59491,Vente,Appartement,104500.0,47.0,2223.40,"Villeneuve-d’Ascq,France"
117844,2025-06-24,WAMBRECHIES,59118,Vente,Maison,731760.0,160.0,4573.50,"Wambrechies 59118,France"
117845,2025-06-30,LAMBERSART,59130,Vente,Maison,390000.0,85.0,4588.24,"Lambersart 59130,France"
117846,2025-06-27,LEERS,59115,Vente,Maison,155000.0,60.0,2583.33,"Leers 59115,France"

ajout du LIB_COM_POSTAL pour pouvoir afficher sur la carte power BI

In [87]:
df["Commune"].unique()

array(['RONCHIN', 'LILLE', 'MARQUETTE-LEZ-LILLE', 'MONS-EN-BAROEUL',
       'LA MADELEINE', 'WAMBRECHIES', 'LAMBERSART', 'SAINT-ANDRE',
       'FACHES-THUMESNIL', 'LEZENNES', 'CROIX', 'ROUBAIX', 'LOOS', 'HEM',
       'WATTIGNIES', 'WILLEMS', 'LYS LEZ LANNOY', 'HAUBOURDIN',
       "VILLENEUVE-D'ASCQ", 'HALLENNES-LEZ-HAUBOURDIN', 'WAVRIN',
       'WASQUEHAL', 'ANSTAING', 'FROMELLES', 'HERLIES', 'LA BASSEE',
       'LESQUIN', 'WATTRELOS', 'LEERS', 'TEMPLEMARS', 'MARQUILLIES',
       'BAISIEUX', 'SANTES', 'HANTAY', 'PROVIN', 'SEQUEDIN', 'CHERENG',
       'SECLIN', 'FRETIN', 'SAINGHIN-EN-WEPPES', 'LANNOY', 'ANNOEULLIN',
       'WICRES', 'ALLENNES-LES-MARAIS', 'RADINGHEM EN WEPPES',
       'SAILLY-LEZ-LANNOY', 'BEAUCAMPS-LIGNY', 'FOREST-SUR-MARQUE',
       'TOUFFLERS', 'EMMERIN', 'SALOME', 'CARNIN',
       'SAINGHIN-EN-MELANTOIS', 'HOUPLIN-ANCOISNE', 'BAUVIN', 'BOUVINES',
       'AUBERS', 'ILLIES', 'NOYELLES-LES-SECLIN', 'VENDEVILLE',
       'FOURNES-EN-WEPPES', 'GRUSON', 'LE MAISNIL', 'DON', 'ESCOBECQUES',
       'ENNETIERES-EN-WEPPES', 'PERONNE-EN-MELANTOIS', 'ENGLOS',
       'ERQUINGHEM-LE-SEC', 'TOURCOING', 'MOUVAUX', 'QUESNOY SUR DEULE',
       'MARCQ EN BAROEUL', 'COMINES', 'HALLUIN', 'ERQUINGHEM-LYS',
       'NEUVILLE EN FERRAIN', 'ARMENTIERES', 'BOUSBECQUE', 'HOUPLINES',
       'RONCQ', 'PERENCHIES', 'BONDUES', 'LA CHAPELLE D ARMENTIERES',
       'BOIS-GRENIER', 'VERLINGHEM', 'PREMESQUES', 'WERVICQ SUD',
       'CAPINGHEM', 'DEULEMONT', 'LINSELLES', 'LOMPRET', 'WARNETON',
       'FRELINGHIEN'], dtype=object)

In [88]:
df["Commune"].nunique()

94

correction des communes pour en obtenir 95

In [90]:
df.to_csv("DVF_MEL.csv", index=False, sep=",")

exctraction en csv