In [5]:
import pandas as pd

percentLogementVacant = pd.read_csv("C:/Users/gromm/Downloads/part_logements_vacants.xlsx - Data.csv")
display(percentLogementVacant)

,Observatoire des territoires - ANCT,Unnamed: 1,Unnamed: 2,Unnamed: 3
0,Insee - RP - données historiques depuis 1968 (...,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,Part des logements vacants
3,codgeo,libgeo,an,part_logt_vacant
4,01,Guadeloupe,1968,"6,20"
...,...,...,...,...
197,94,Corse,2011,"3,70"
198,94,Corse,2015,"3,40"
199,94,Corse,2016,"3,30"
200,94,Corse,2021,"3,10"
201,94,Corse,2022,"3,30"

In [ ]:
# Renamed columns

percentLogementVacant.columns = ["code_geo", "lib_geo", "année", "part_logements_vacants"]

# Removed the 4 first rows

percentLogementVacant = percentLogementVacant.drop(percentLogementVacant.index[:4])
display(percentLogementVacant)

    code_geo     lib_geo année part_logements_vacants
4         01  Guadeloupe  1968                   6,20
5         01  Guadeloupe  1975                  13,70
6         01  Guadeloupe  1982                  13,40
7         01  Guadeloupe  1990                   9,60
8         01  Guadeloupe  1999                  13,30
..       ...         ...   ...                    ...
197       94       Corse  2011                   3,70
198       94       Corse  2015                   3,40
199       94       Corse  2016                   3,30
200       94       Corse  2021                   3,10
201       94       Corse  2022                   3,30

[198 rows x 4 columns]

In [ ]:
# Kept only the "Hauts-de-France" values

percentLogementVacant = percentLogementVacant[percentLogementVacant['code_geo'].str.startswith('32')]
display(percentLogementVacant)

    code_geo          lib_geo année part_logements_vacants
103       32  Hauts-de-France  1968                   5,30
104       32  Hauts-de-France  1975                   6,10
105       32  Hauts-de-France  1982                   7,00
106       32  Hauts-de-France  1990                   7,00
107       32  Hauts-de-France  1999                   5,60
108       32  Hauts-de-France  2010                   6,20
109       32  Hauts-de-France  2011                   6,50
110       32  Hauts-de-France  2015                   7,60
111       32  Hauts-de-France  2016                   7,80
112       32  Hauts-de-France  2021                   7,70
113       32  Hauts-de-France  2022                   7,50

In [ ]:
# Export

percentLogementVacant.to_csv("PartLogementsVacants.csv", index = False)