In [12]:
import pandas as pd

importation du fichier des logements vacants ==>

In [35]:
df = pd.read_excel("/data/Projet_reconversion/Projet et cours Data Analyst/Cours Le Wagon/projet_crise_logement/Donnees a nettoyer/Immobilier/Nature_des_logements/LogementsVacants_France.xlsx", sheet_name="COM")
df.head(5)

,CODGEO_25,LIBGEO_25,pp_vacant_25,pp_vacant_plus_2ans_25,pp_total_24,pp_vacant_24,pp_vacant_plus_2ans_24,pp_total_23,pp_vacant_23,pp_vacant_plus_2ans_23,...,pp_vacant_plus_2ans_21,pp_total_20,pp_vacant_20,pp_vacant_plus_2ans_20,EPCI_25,LIB_EPCI_25,DEP,LIB_DEP,REG,LIB_REG
0,01001,L'Abergement-Clémenciat,s,s,358,15,s,355,15,s,...,s,339,20,s,200069193,Communauté de communes de la Dombes,01,Ain,84,Auvergne-Rhône-Alpes
1,01002,L'Abergement-de-Varey,s,s,180,11,s,180,s,s,...,s,181,13,s,240100883,Communauté de communes de la Plaine de l'Ain,01,Ain,84,Auvergne-Rhône-Alpes
2,01004,Ambérieu-en-Bugey,374,207,5949,628,200,5918,626,188,...,190,5776,679,163,240100883,Communauté de communes de la Plaine de l'Ain,01,Ain,84,Auvergne-Rhône-Alpes
3,01005,Ambérieux-en-Dombes,28,13,809,61,s,795,39,s,...,s,693,38,s,200042497,Communauté de communes Dombes Saône Vallée,01,Ain,84,Auvergne-Rhône-Alpes
4,01006,Ambléon,s,s,s,s,s,s,s,s,...,s,s,s,s,200040350,Communauté de communes Bugey Sud,01,Ain,84,Auvergne-Rhône-Alpes

Filtre par "Métropole Européenne de Lille" pour ne garder que la métropole lilloise

In [ ]:
df_mel = df[df["LIB_EPCI_25"]=="Métropole Européenne de Lille"]

,CODGEO_25,LIBGEO_25,pp_vacant_25,pp_vacant_plus_2ans_25,pp_total_24,pp_vacant_24,pp_vacant_plus_2ans_24,pp_total_23,pp_vacant_23,pp_vacant_plus_2ans_23,...,pp_vacant_plus_2ans_21,pp_total_20,pp_vacant_20,pp_vacant_plus_2ans_20,EPCI_25,LIB_EPCI_25,DEP,LIB_DEP,REG,LIB_REG
21760,59005,Allennes-les-Marais,44,20,1376,64,s,1371,57,s,...,13,1340,79,s,200093201,Métropole Européenne de Lille,59,Nord,32,Hauts-de-France
21764,59009,Villeneuve-d'Ascq,743,289,17035,1562,240,16754,1608,179,...,196,15541,1228,179,200093201,Métropole Européenne de Lille,59,Nord,32,Hauts-de-France
21766,59011,Annœullin,139,68,3788,245,56,3771,192,66,...,66,3708,286,68,200093201,Métropole Européenne de Lille,59,Nord,32,Hauts-de-France
21768,59013,Anstaing,21,s,598,29,s,597,29,s,...,s,581,56,s,200093201,Métropole Européenne de Lille,59,Nord,32,Hauts-de-France
21772,59017,Armentières,845,407,10345,1444,338,10103,1375,320,...,345,9695,1203,332,200093201,Métropole Européenne de Lille,59,Nord,32,Hauts-de-France
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22385,59653,Wavrin,87,41,2825,131,27,2814,165,23,...,22,2799,135,20,200093201,Métropole Européenne de Lille,59,Nord,32,Hauts-de-France
22388,59656,Wervicq-Sud,54,30,1696,78,20,1667,78,20,...,16,1594,110,15,200093201,Métropole Européenne de Lille,59,Nord,32,Hauts-de-France
22390,59658,Wicres,s,s,206,13,s,203,11,s,...,s,187,13,s,200093201,Métropole Européenne de Lille,59,Nord,32,Hauts-de-France
22392,59660,Willems,37,11,1014,56,s,1008,37,s,...,s,1001,64,s,200093201,Métropole Européenne de Lille,59,Nord,32,Hauts-de-France
22402,59670,Don,13,s,564,26,s,561,17,s,...,s,538,46,s,200093201,Métropole Européenne de Lille,59,Nord,32,Hauts-de-France

Export en fichier csv exploitable

In [46]:
df.to_csv("logement_vacants_MEL.csv", index=False)